try {
  let student;
  console.log(student.name);
} catch(err) {
  console.log("Error caught:", err.message);
}
