// Example: catch
Promise.reject("Something went wrong")
  .catch(err => console.log("Error:", err));
