try {
  let x = 5 / 0;
  console.log(x);
} catch (error) {
  console.log("Error occurred:", error);
}
